apiVersion: v1
kind: Namespace
metadata:
  name: obligax
  labels:
    app.kubernetes.io/name: obligax
    app.kubernetes.io/part-of: obligax-network
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
