canton {
  synchronizers {
    synchronizer1 {
      storage {
        type = memory
      }
      sequencer {
        type = reference
        public-api {
          address = "0.0.0.0"
          port = 5018
        }
        admin-api {
          address = "0.0.0.0"
          port = 5019
        }
      }
      mediator {
        admin-api {
          address = "0.0.0.0"
          port = 5017
        }
      }
      admin-api {
        address = "0.0.0.0"
        port = 5028
      }
    }
  }
}
